name: Build app

env:
  ORG_GRADLE_PROJECT_githubUser: ${{ github.actor }}
  ORG_GRADLE_PROJECT_githubPackagesReadToken: ${{ secrets.GH_PACKAGES_READ_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DOCKER_IMAGE: bartbednarek/multiple-docker-build-app
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      

      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Build Project
        run: ./gradlew clean build --no-daemon

      - name: Set Docker Image
        run: echo "TF_VAR_image=${{ env.DOCKER_IMAGE }}:$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Docker Build & Push
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew :app:jib --no-daemon --image=$TF_VAR_image
