name: Dependent

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#  workflow_dispatch:
  workflow_run:
    workflows: [Main]
    types: [completed]
#    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: | 
          echo "Dependent workflow"
          sleep 10
