name: CI - release

env:
  ORG_GRADLE_PROJECT_githubUser: ${{ github.actor }}
  ORG_GRADLE_PROJECT_githubToken: ${{ github.token }}
  ORG_GRADLE_PROJECT_githubPackagesReadToken: ${{ secrets.GH_PACKAGES_READ_TOKEN }}

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Gradle Build
        run: ./gradlew -Pversion=${{ github.event.release.tag_name }} clean build --no-daemon

      - name: Gradle Publish
        run: ./gradlew -Pversion=${{ github.event.release.tag_name }} publish
